---
- name: Restart Djavan stack
  hosts: local
  become: true
  become_user: root
  tasks:

  - name: stop services
    service: name="{{item}}" state=stopped
    with_items:
      - djavan
      - nginx

  - name: start services
    service: name="{{item}}" state=started
    with_items:
      - nginx
      - djavan

